services:
  - type: web
    name: insurance-predictor-api
    runtime: python
    buildCommand: "pip install --upgrade pip && pip install --only-binary=all -r requirements.txt"
    startCommand: uvicorn app1:app --host 0.0.0.0 --port $PORT
    
